version: "3"

services:
  api:
    build: app/MyApi
    expose:
      - "80"

  lb:
    image: nginx:latest
    volumes:
      - ./lb/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./sre/prometheus:/etc/prometheus
      # - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 9099:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./sre/grafana:/etc/grafana/provisioning/datasources
      - grafana_storage:/var/lib/grafana
volumes:
  # prom_data:
  grafana_storage:
